### ISSUE TITLE
SDL_CreateWindow doesn't show the window unless I also call SDL_UpdateWindowSurface

### ISSUE THREAD

**Issue by dblevins-3dgfx** [MikeShah/SDL2_Tutorials#1]
HW: HP Chromebook
OS: Version 94.0.4606.114 (Official Build) (64-bit)
SDL version: 2.0.9

https://github.com/MikeShah/SDL2_Tutorials/blob/ec5000a45e9ea403ddb1fc6b8b0127f258260942/2_Window/main.cpp#L30

The SDL_CreateWindow succeeds (returns non-null), but no window is displayed. I find if I add the following code after the call, it does display:

```
    (void)SDL_GetWindowSurface(window);
    SDL_UpdateWindowSurface(window);
```

**Comment by MikeShah** [comment]
Strange, I wonder what GPU you have? Perhaps the driver is doing some sort of lazy initialization.

Can you confirm if the other lessons (e.g. TexturedRectangle) exhibit this behavior? I am assuming they would not since there is an update loop that refreshes the window surface.
